apiVersion: v1
kind: Service
metadata:
  name: {{ include "psstd.fullname" . }}
spec:
  selector: {{ include "psstd.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
